config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit] do
      #collection do
      #  get 'admin'
      #end
      resources :docs, except: [:new, :edit]
    end

    resources :docs, except: [:new, :edit]
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts

    resources :users

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote
    get 'result' => 'result#index', as: :result
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale
  get '/set_client_id' => 'users#set_client_id', as: :set_client_id

  # Admin Routes

  scope 'admin' do

    get '/' => 'admin#tickets', as: :admin

    resources :docs, only: [:new, :edit]
    resources :knowledgebase, :as => 'categories', :controller => "categories", only: [:new, :edit] do
      resources :docs, only: [:new, :edit]
    end

    get '/dashboard' => 'admin#dashboard', as: :admin_dashboard
    get '/content' => 'admin#knowledgebase', as: :admin_knowledgebase
    get '/content/:category_id/articles' => 'admin#articles', as: :admin_articles
    post '/content/update_order' => 'admin#update_order', as: :admin_update_order
    get '/tickets' => 'admin#tickets', as: :admin_tickets
    get '/ticket/:id' => 'admin#ticket', as: :admin_ticket
    get '/tickets/new' => 'admin#new_ticket', as: :admin_new_ticket
    post '/tickets/create' => 'admin#create_ticket', as: :admin_create_ticket
    get '/tickets/update' => 'admin#update_ticket', as: :update_ticket, defaults: {format: 'js'}
    get '/tickets/update_multiple' => 'admin#update_multiple_tickets', as: :update_multiple_tickets
    get '/tickets/assign_agent' => 'admin#assign_agent', as: :assign_agent
    get '/tickets/toggle_privacy' => 'admin#toggle_privacy', as: :toggle_privacy
    get '/tickets/:id/toggle' => 'admin#toggle_post', as: :toggle_post
    get '/communities' => 'admin#communities', as: :admin_communities
    #get '/users'
    get '/user/:id/edit' => 'admin#edit_user', as: :admin_user
    get '/user/:id' => 'admin#user_profile', as: :user_profile
    get '/topic_search' => 'admin#topic_search', as: :admin_search
    get '/user_search' => 'admin#user_search', as: :user_search

  end




  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/controllers/result_controller.rb
class ResultController < ApplicationController


  def index

    @results = PgSearch.multisearch(params[:q]).page params[:page]
    @page_title = I18n.translate(:how_can_we_help, default: "How can we help?")
    add_breadcrumb 'Search'

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/result/_results_found.html.erb
<h4>
  <span id="results-total-count">
    <%= t(:results_found, :count => @results.total_count) %>
  </span>
  <strong>"<%= params[:q] %>"</strong>
</h4>

app/views/result/_search_form.html.erb
<div class="form-group has-feedback right-inner-addon">
  <%= form_tag result_path, method: :get, id: 'search-form', remote: (params[:controller] == 'result') do %>
    <div class="input-group">
      <%= text_field_tag('q', nil, placeholder: t(:search_placeholder, default: "Enter a keyword, topic, or question"), id: 'search-field', class: 'form-control', value: params[:q]) %>
      <div class="input-group-btn">
        <button type="submit" class="btn btn-default" aria-label="Search">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </div>
    </div>
  <% end # form %>
</div>

app/views/result/_search_results.html.erb
<ul class="list-unstyled">
<% @results.each do |result| %>
  <% if result.searchable_type == "Topic" %>
  <li class="search-result">
    <span class="more-important"><%= link_to result.searchable.name, topic_posts_path(Topic.find(result.searchable_id)) %></span><br/>
    <span class="result-body less-important"><%= strip_tags result.searchable.post_cache.truncate_words(20) %></span><br/><br/>
  </li>
  <% else %>
  <li class="search-result">
    <span class="more-important"><%= link_to result.searchable.title, category_doc_path(result.searchable.category_id, Doc.find(result.searchable_id)) %></span><br/>
    <span class="result-body less-important"><%= strip_tags(result.searchable.body.truncate_words(20)) unless result.searchable.body.nil? %></span><br/><br/>
  </li>
  <% end %>
<% end %>
<% if @results.total_count == 0 %>
  <li class="text-center verticalness"><%= t(:no_results) %></li>
<% end %>
</ul>
<div class="text-center paginate-links">
  <%= paginate @results, :remote => true %>
</div>

app/views/result/index.html.erb
<% if params[:q] %>
  <div id="results-found">
  <%= render 'results_found' %>
  </div>
<% end %>


<div id="search-results">
  <%= render 'search_results' %>
</div>