config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit] do
      #collection do
      #  get 'admin'
      #end
      resources :docs, except: [:new, :edit]
    end

    resources :docs, except: [:new, :edit]
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts

    resources :users

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote
    get 'result' => 'result#index', as: :result
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale
  get '/set_client_id' => 'users#set_client_id', as: :set_client_id

  # Admin Routes

  scope 'admin' do

    get '/' => 'admin#tickets', as: :admin

    resources :docs, only: [:new, :edit]
    resources :knowledgebase, :as => 'categories', :controller => "categories", only: [:new, :edit] do
      resources :docs, only: [:new, :edit]
    end

    get '/dashboard' => 'admin#dashboard', as: :admin_dashboard
    get '/content' => 'admin#knowledgebase', as: :admin_knowledgebase
    get '/content/:category_id/articles' => 'admin#articles', as: :admin_articles
    post '/content/update_order' => 'admin#update_order', as: :admin_update_order
    get '/tickets' => 'admin#tickets', as: :admin_tickets
    get '/ticket/:id' => 'admin#ticket', as: :admin_ticket
    get '/tickets/new' => 'admin#new_ticket', as: :admin_new_ticket
    post '/tickets/create' => 'admin#create_ticket', as: :admin_create_ticket
    get '/tickets/update' => 'admin#update_ticket', as: :update_ticket, defaults: {format: 'js'}
    get '/tickets/update_multiple' => 'admin#update_multiple_tickets', as: :update_multiple_tickets
    get '/tickets/assign_agent' => 'admin#assign_agent', as: :assign_agent
    get '/tickets/toggle_privacy' => 'admin#toggle_privacy', as: :toggle_privacy
    get '/tickets/:id/toggle' => 'admin#toggle_post', as: :toggle_post
    get '/communities' => 'admin#communities', as: :admin_communities
    #get '/users'
    get '/user/:id/edit' => 'admin#edit_user', as: :admin_user
    get '/user/:id' => 'admin#user_profile', as: :user_profile
    get '/topic_search' => 'admin#topic_search', as: :admin_search
    get '/user_search' => 'admin#user_search', as: :user_search

  end




  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#

class Topic < ActiveRecord::Base

  include SentenceCase

  belongs_to :forum, counter_cache: true, touch: true
  belongs_to :user, counter_cache: true, touch: true
  belongs_to :assigned_user, class_name: 'User'

  has_many :posts, :dependent => :delete_all
  has_many :votes, :as => :voteable
  has_attachments  :screenshots, accept: [:jpg, :png, :gif]

  paginates_per 25

  include PgSearch
  multisearchable :against => [:id, :name, :post_cache],
                  :if => :public

  pg_search_scope :admin_search,
                  against: [:id, :name, :user_name, :current_status, :post_cache]

  # various scopes
  scope :recent, -> { order('created_at DESC').limit(8) }
  scope :open, -> { where(current_status: "open") }
  scope :unread, -> { where(current_status: "new") }
  scope :pending, -> { where(current_status: "pending") }
  scope :mine, -> (user) { where(assigned_user_id: user) }
  scope :closed, -> { where(current_status: "closed") }
  scope :spam, -> { where(current_status: "spam")}

  scope :chronologic, -> { order('updated_at DESC') }
  scope :by_popularity, -> { order('points DESC') }
  scope :active, -> { where(current_status: %w(open pending)) }
  scope :undeleted, -> { where.not(current_status: 'trash') }
  scope :front, -> { limit(6) }

  # provided both public and private instead of one method, for code readability
  scope :isprivate, -> { where.not(current_status: 'spam').where(private: true)}
  scope :ispublic, -> { where.not(current_status: 'spam').where(private: false)}

  # may want to get rid of this filter:
  # before_save :check_for_private
  before_create :cache_user_name
  before_create :add_locale

  # acts_as_taggable

  validates_presence_of :name
  validates_length_of :name, :maximum => 255

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def email_subject
    "##{self.id} | #{self.name}"
  end

  def open?
    self.current_status == "open"
  end

  def open
    self.current_status = "pending"
    self.save
  end

  def reopen(user_id = 2)
    self.posts.create(body: I18n.t(:reopen_message, user_name: User.find(user_id).name), kind: 'note', user_id: user_id)
    self.current_status = "open"
    self.save
  end

  def close(user_id = 2)
    self.posts.create(body: I18n.t(:close_message, user_name: User.find(user_id).name), kind: 'note', user_id: user_id)
    self.current_status = "closed"
    self.closed_date = Time.now
    self.assigned_user_id = nil
    self.save
  end

  def trash(user_id = 2)
    self.posts.create(body: I18n.t(:trash_message, user_name: User.find(user_id).name), kind: 'note', user_id: user_id)
    self.current_status = "trash"
    self.closed_date = Time.now
    self.forum_id = 2
    self.private = true
    self.assigned_user_id = nil
    self.save
  end

  def assign(user_id=2, assigned_to)
    self.posts.create(body: I18n.t(:assigned_message, assigned_to: User.find(assigned_to).name), kind: 'note', user_id: user_id)
    self.assigned_user_id = assigned_to
    self.current_status = 'pending'
    self.save
  end

  # DEPRECATED updates the last post date, called when a post is made
  def self.last_post
    Topic.post(:first, :order => 'updated_at DESC')
  end

  #Callback method to check and see if this topic is in a private forum
  def check_for_private
    #association is not working
    f = Forum.find(self.forum_id)
    self.private = true if f.private?
  end

  # TODO: This is better named 'public?'
  def public
    # Note: We assume forum_ids 1,2,3 are seed data
    forum_id >= 3 && !private?
  end

  private

  def cache_user_name
    self.user_name = self.user.name
  end

  def add_locale
    self.locale = I18n.locale
  end
end

app/controllers/topics_controller.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#

class TopicsController < ApplicationController

  before_action :authenticate_user!, :except => ['show','index','tag','make_private', 'new', 'create', 'up_vote']
  before_action :instantiate_tracker

  layout "clean", only: [:new, :index]

  # GET /topics
  # GET /topics.xml
  def index
    @forum = Forum.ispublic.where(id: params[:forum_id]).first
    if @forum
      if @forum.allow_topic_voting == true
        @topics = @forum.topics.ispublic.by_popularity.page params[:page]
      else
        @topics = @forum.topics.ispublic.chronologic.page params[:page]
      end

      #@feed_link = "<link rel='alternate' type='application/rss+xml' title='RSS' href='#{forum_topics_url}.rss' />"

      @page_title = @forum.name
      @title_tag = "#{Settings.site_name}: #{@page_title}"
      add_breadcrumb t(:community, default: "Community"), forums_path
      add_breadcrumb @forum.name
    end

    respond_to do |format|
      if @forum
        format.html # index.rhtml
        format.xml  { render :xml => @topics.to_xml }
        format.rss
      else
        format.html { redirect_to root_path }
      end
    end
  end

  def tickets

    @topics = current_user.topics.isprivate.undeleted.chronologic.page params[:page]
    @page_title = t(:tickets, default: 'Tickets')
    add_breadcrumb @page_title

    @title_tag = "#{Settings.site_name}: #{@page_title}"

    #@feed_link = "<link rel='alternate' type='application/rss+xml' title='RSS' href='#{forum_topics_url}.rss' />"

    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @topics.to_xml }
      format.rss
    end
  end


  def ticket

    @topic = current_user.topics.undeleted.where(id: params[:id]).first
    if @topic
      @posts = @topic.posts.ispublic.chronologic.active.all

      @page_title = "##{@topic.id} #{@topic.name}"
      add_breadcrumb t(:tickets, default: 'Tickets'), tickets_path
      add_breadcrumb @page_title

      @title_tag = "#{Settings.site_name}: #{@page_title}"
    end

    respond_to do |format|
      if @topic
        format.html # index.rhtml
        format.xml  { render :xml => @topics.to_xml }
        format.rss
      else
        format.html { redirect_to root_path}
      end
    end


  end


  # GET /topics/1
  # GET /topics/1.xml
  def show

  end

  # GET /topics/new
  def new

    @page_title = t(:start_discussion, default: "Start a New Discussion")
    add_breadcrumb @page_title
    @title_tag = "#{Settings.site_name}: #{@page_title}"

    @forums = Forum.ispublic.all
    @topic = Topic.new
    @user = @topic.build_user unless user_signed_in?

  end

  # GET /topics/1;edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create

    @page_title = t(:start_discussion, default: "Start a New Discussion")
    add_breadcrumb @page_title
    @title_tag = "#{Settings.site_name}: #{@page_title}"

    params[:id].nil? ? @forum = Forum.find(params[:topic][:forum_id]) : @forum = Forum.find(params[:id])
    logger.info(@forum.name)

    @topic = @forum.topics.new(
      name: params[:topic][:name],
      private: params[:topic][:private] )

    unless user_signed_in?

      # User is not signed in, lets see if we can recognize the email address
      @user = User.where(email: params[:topic][:user][:email]).first

      if @user
        logger.info("User found")
        @topic.user_id = @user.id

      else #User not found, lets build it

        @user = @topic.build_user

        @token, enc = Devise.token_generator.generate(User, :reset_password_token)
        @user.reset_password_token = enc
        @user.reset_password_sent_at = Time.now.utc

        @user.name = params[:topic][:user][:name]
        @user.login = params[:topic][:user][:email].split("@")[0]
        @user.email = params[:topic][:user][:email]
        @user.password = User.create_password
        built_user = true
      end

    else
      @user = current_user
      @topic.user_id = @user.id

    end

    if @user.save && @topic.save

      @post = @topic.posts.create(
        :body => params[:post][:body],
        :user_id => @user.id,
        :kind => 'first',
        :screenshots => params[:topic][:screenshots])

      if built_user == true && !user_signed_in?
        UserMailer.new_user(@user, @token).deliver_now
      end

      # track event in GA
      @tracker.event(category: 'Request', action: 'Post', label: 'New Topic')
      @tracker.event(category: 'Agent: Unassigned', action: 'New', label: @topic.to_param)

      if @topic.private?
        redirect_to ticket_path(@topic)
      else
        redirect_to topic_posts_path(@topic)
      end
    else
      render :new
    end

  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])
    @topic.tag_list = params[:tags]
    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        #flash[:notice] = 'Topic was successfully updated.'
        format.html { redirect_to topic_posts_path(@topic) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors.to_xml }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.posts.each { |post| post.destroy }
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to forum_topics_path(@topic.forum) }
      format.xml  { head :ok }
    end
  end

  def up_vote

    if user_signed_in?
      @topic = Topic.find(params[:id])
      @topic.votes.create(user_id: current_user.id)
      @topic.touch
      @topic.reload
    end
    respond_to do |format|
      format.js
    end

  end

  def tag
    @topics = Topic.ispublic.tag_counts_on(:tags)
  end
end

app/helpers/topics_helper.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#

module TopicsHelper

  def badge_for_status(status)
    content_tag(:span, status_label(status).upcase, class: "hidden-xs pull-right status-label label #{status_class(status)}")
  end

  def badge_for_private
    content_tag(:span, t(:private, default: 'PRIVATE').upcase, class: 'hidden-xs pull-right status-label label label-private')
  end

  def control_for_status(status)
    content_tag(:span, "#{status_label(status).upcase} <span class='caret'></span> ".html_safe, class: "btn status-label label #{status_class(status)}")
  end

  def control_for_privacy(private_flag)
    str = private_flag ? t(:private, default: 'PRIVATE') : t(:public, default: 'PUBLIC')
    content_tag(:span, "#{str} <span class='caret'></span> ".html_safe, class: 'btn privacy-label label label-info')
  end

  def assigned_badge(topic)
    if topic.assigned_user_id.nil?
      "<span class='btn status-label label label-warning'>#{t(:unassigned, default: 'UNASSIGNED')}<span class='caret'></span> </span>"
    else
      "<span class='btn status-label label label-warning'>#{topic.assigned_user.name.upcase} <span class='caret'></span> </span>"
    end
  end

  def status_label(status)
    case status
      when 'new'
        t(:new, default: 'new')
      when 'open'
        t(:open, default: 'open')
      when 'active'
        t(:active, default: 'active')
      when 'assigned'
        t(:mine, default: 'mine')
      when 'closed'
        t(:closed, default: 'resolved')
      when 'pending'
        t(:pending, default: 'pending')
      when 'spam'
        t(:spam, default: 'spam')
      when 'trash'
        t(:trash, default: 'trash')
    end
  end

  def status_class(status)
    case status
      when 'new'
        'label-info'
      when 'open'
        'label-success'
      when 'closed'
        'label-default'
      when 'pending'
        'label-warning'
      when 'spam'
        'label-danger'
      when 'trash'
        'label-danger'
    end
  end


end

app/views/topics/_grid.html.erb
  <div class="idea-box col-lg-3 col-md-3 col-sm-4 col-xs-12" data-link="<%= topic_posts_path(grid) %>">
    <div class="dummy"></div>
    <div class="thumbnail">
      <span class="more-important truncate-ellipsis text-left">
        <%= link_to h(grid.name), topic_posts_path(grid) %>
      </span>
      <div class="text-left">
         <%= grid.posts_count %> comments
      </div>
      <% if grid.forum.allow_post_voting == true %>
      <div id="post-vote-<%= grid.posts.first.id %>" class="grid-vote text-right">
        <%= link_to t(:upvote, count: grid.points), up_vote_path(grid.id), method: :post, remote: true, class: 'topic-vote', data: {voted: grid.to_param} %>
      </div>
      <% end %>
    </div>

  </div>

app/views/topics/_qna.html.erb
<% post = qna.posts.by_votes.first %>

  <div id="post-<%= post.id %>" class="media post-container kind-first<%= " inactive" unless post.active? %>">
    <div class="asked-question">
      <%= distance_of_time_in_words(Time.now,qna.created_at) %> ago <%= post_message(qna.posts.first) %>
    </div>
    <h4 class="qna"><%= link_to h(qna.name), topic_posts_path(qna) -%></h4>



    <div class="pull-left">
  		<%#= image_tag(post.user.image_url, width: '40px', class: 'media-object img-circle') %>
      <%= avatar_image(post.user, size=40) %>
  	</div>
  	<div class="media-body media-right">
  		<span class="hidden-sm hidden-md hidden-lg"><%= post.kind == "first" ? last_active_time(post.created_at) : "#{distance_of_time_in_words(post.created_at,post.topic.created_at)} later" %><br/></span>
  		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
        <%= post_message(post) %>
  			<% if user_signed_in? && current_user.admin? && params[:controller] == 'admin' %>
  				<ul class="dropdown-menu dropdown-menu-left" role="menu">
  					<li><%= link_to 'Edit', edit_post_path(post), remote: true %></li>
  					<li><%= link_to 'Turn post into content', new_doc_path(post_id: post.id, lang: I18n.locale) %></li>
  				</ul>
  			<% end %>
  		</span>

  		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
  			<span class="shorten"><%= simple_format(post.body) -%></span>

        <% if post.topic.forum.allow_post_voting == true %>
  			<div id="post-vote-<%= post.id %>" class="btn btn-default">
  				<% if post.kind == 'first' %>
  				<%= link_to t(:upvote, count: post.topic.points), up_vote_path(post.topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: post.topic.to_param} %>
  				<% else %>
  				<%= link_to t(:upvote, count: post.points), post_vote_path(post.id), method: :post, remote: true, class: 'post-vote', data: {voted: post.topic.to_param} %>
  				<% end %>
  			</div>
  			<% end %>

  		</div>



  	</div>
  </div>

<hr/>

app/views/topics/_ticket.html.erb
<tr class="topic border-bottom">
  <td>
    <span class="truncate-ellipsis">
      <%= link_to "##{ticket.id}- #{ticket.name.capitalize}", ticket_path(ticket) -%><%= badge_for_status(ticket.current_status) %>
    </span>
  </td>
  <td class="last-active less-important text-right">
    <span class="label label-count hidden-xs pull-left"><%= ticket.posts_count %></span>
    <%= last_active_time(ticket.updated_at) %>
  </td>
</tr>

app/views/topics/_topic.html.erb
<tr id="topic_<%= topic.id %>" class="topic link-row">
  <% if topic.forum.allow_topic_voting == true %>
  <td>

    <div class="voting-widget">
      <!--<span class="glyphicon glyphicon-plus-sign"></span>-->
      <div class="vote-icon glyphicon glyphicon-chevron-up"></div>
      <div class="topic-points"><%= link_to topic.points, up_vote_path(topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: topic.to_param} %></div>
    </div>
  </td>
  <% end %>
  <td>
    <span class="more-important truncate-ellipsis"><%= link_to h(topic.name), topic_posts_path(topic) -%></span>
    <span class="less-important"><%= t(:started_by, :username => topic.user.name.titleize) %></span>
  </td>
  <td>
    <span class="label label-count hidden-xs"><%= topic.posts_count %></span>
  </td>
  <td class="last-active less-important text-right">
    <%= last_active_time(topic.last_post_date) %>
  </td>
</tr>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%#= error_messages_for :topic %>

  <%= form_for(:topic, :url => topic_path(:id => @topic, :forum_id => @topic.forum),
       :html => { :method => :put }) do |f| %>
    <label>Subject:</label><br /><%= f.text_field :name, :size => 40 -%><br/><br/>
	<label>Category:</label><br/><%= collection_select("topic", "forum_id", Forum.all, :id, :name) %><br/><br/>
	<label>Tags:</label><br/><%= text_field_tag :tags, @topic.tag_list %>

  <p>
    <%= submit_tag "Update" %>
  </p>
<% end %>

app/views/topics/index.html.erb
<% if @forum.layout == "table" %>

<table id="forums" class="table-hover">

  <% if @forum.allow_topic_voting == true %>
  <col width="5%">
  <% end %>
  <col>
  <col width="5%">
  <col width="10%">

  <tbody>
    <tr>
      <% if @forum.allow_topic_voting == true %>
      <th colspan="3">
      <% else %>

      <th colspan="2">
      <% end %>
        <%= t(:topic) %></th>
  	  <th class="text-right"><%= t(:last_activity) %></th>
    </tr>
    <%= render :partial => 'topic', :collection => @topics %>
  </tbody>
</table>

<% elsif @forum.layout == "grid" %>
<div id="featured-categories" class="row">
  <%= render :partial => 'grid', :collection => @topics %>
</div>

<% elsif @forum.layout == "qna" %>
<div class="row">
	<div class="col-md-12">
    <div id="qnas">
      <%= render :partial => 'qna', :collection => @topics %>
    </div>
  </div>
</div>
<% end %>



<div class="text-right">
	<%= paginate @topics %>
</div>

<div>
  <% if user_signed_in? %>
    <span class="hidden-xs pull-right"><%= link_to t(:open_new_discussion, default: "Open Discussion"), new_topic_path, class: 'btn btn-primary' %></span>
  <% else %>
    <span class="hidden-xs pull-right"><%= link_to t(:open_new_discussion, default: "Open Discussion"), '#', data: {toggle: "modal", target: "#login-modal"}, class: 'btn btn-primary' %></span>
  <% end %>
</div>

app/views/topics/tag.html.erb
<div id="breadcrumbs">
  <%= link_to 'Forums', forums_path -%> > <strong>Tagged with <%= h params[:id] -%></strong>
</div>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>

<table id="topics">
	
  <col width="55%">
  <col width="5%">
  <col width="10%">
  <col width="5%">	
  <col width="20%">		
	
  <tr>
    <th colspan="2">Topic</th>
    <th>Status</th>
    <th>Replies</th>
	<th>Last Post</th>	
  </tr>
  <%= render :partial => 'topic', :collection => @topics %>
</table>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>

app/views/topics/ticket.html.erb
<div id="ticket-info" class="row">

  <div class="col-md-3 col-sm-3 hidden-xs" id="left-col-user-info">


    <div class="doc-meta">
      <div class="more-important meta-header">Ticket Number:</div>
      <div class="less-important"><%= @topic.id %></div>
    </div>

    <div class="doc-meta">
      <div class="more-important meta-header"><%= I18n.t('assigned_to_label', default: "Assigned To") %>:</div>
      <div class="less-important">
        <% unless @topic.assigned_user.nil? %>
          <%= avatar_image(@topic.assigned_user, size=40) %>
          <%= @topic.assigned_user.name.titleize %>
        <% else %>
          Unassigned
        <% end %>
      </div>
    </div>

    <div class="doc-meta">
      <div class="more-important meta-header">Opened On:</div>
      <div class="less-important"><%= @topic.created_at %></div>
    </div>



    <%#= render 'admin/user_info' %>
    <!--<span class="btn-group left-col-dropdown">
      <span class="status dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
        Ticket Status: <%= control_for_status(@topic.current_status).html_safe %>
      </span>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to 'Mark Closed', update_ticket_path(@topic, change_status: 'closed'), :remote => true unless @topic.current_status == "closed" %></li>
        <li><%= link_to 'Reopen', update_ticket_path(@topic, change_status: 'open'), :remote => true unless @topic.current_status == "open" %></li>
        <li><%= link_to 'Mark New', update_ticket_path(@topic, change_status: 'new'), :remote => true unless @topic.current_status == "new" %></li>
        <li><%= link_to 'Mark Spam', update_ticket_path(@topic, change_status: 'spam'), :remote => true unless @topic.current_status == "spam" %></li>
      </ul>
    </span> -->
  </div>

  <div id="ticket-controls" class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
    <script>
      Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
    </script>
    <div id="posts">
      <%= render :partial => 'posts/post', :collection => @posts %>
    </div>

    <% if user_signed_in? %>
      <div class="add-form">
      <h4><%= I18n.t("reply", default: "Reply to this Topic") %></h4>
      <%#= error_messages_for :post -%>
      <%= bootstrap_form_for @topic.posts.new, :url => topic_posts_path(@topic), :remote => true do |f| -%>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <%= f.hidden_field 'kind', value: 'reply' %>
        <%= hidden_field_tag :client_id %>
        <%= f.text_area :body, :rows => 8, :cols => 160, skip_label: true -%></p>
        <%= f.attachinary_file_field :screenshots unless Cloudinary.config.cloud_name.nil? %>
        <%= f.submit I18n.t('submit_reply', default: 'Post Reply'), class: 'btn btn-warning' -%>
      <% end -%>
      </div>
    <% end -%>
  </div>



</div>

app/views/topics/tickets.html.erb
<table id="topics" class="forum table-hover">

  <col>
  <col width="20%">

  <tr>
    <th><%= t(:topic) %></th>
    <th class="text-right"><%= t(:last_activity) %></th>
  </tr>
  <%= render :partial => 'topics/ticket', :collection => @topics %>
</table>

<% if @topics.total_count == 0 %>
  <div class="text-center verticalness"><%= t(:no_tickets) %></div>
<% end %>


<div class="text-right">
  <%= paginate @topics %>
</div>

app/views/topics/up_vote.js.erb
<% if user_signed_in? %>
$('#topic_<%= @topic.id %>').replaceWith("<%= j(render partial: 'topics/topic', locals: {topic: @topic}) %>");
<% else %>
$('.login-link').click();
<% end %>