config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit] do
      #collection do
      #  get 'admin'
      #end
      resources :docs, except: [:new, :edit]
    end

    resources :docs, except: [:new, :edit]
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts

    resources :users

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote
    get 'result' => 'result#index', as: :result
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale
  get '/set_client_id' => 'users#set_client_id', as: :set_client_id

  # Admin Routes

  scope 'admin' do

    get '/' => 'admin#tickets', as: :admin

    resources :docs, only: [:new, :edit]
    resources :knowledgebase, :as => 'categories', :controller => "categories", only: [:new, :edit] do
      resources :docs, only: [:new, :edit]
    end

    get '/dashboard' => 'admin#dashboard', as: :admin_dashboard
    get '/content' => 'admin#knowledgebase', as: :admin_knowledgebase
    get '/content/:category_id/articles' => 'admin#articles', as: :admin_articles
    post '/content/update_order' => 'admin#update_order', as: :admin_update_order
    get '/tickets' => 'admin#tickets', as: :admin_tickets
    get '/ticket/:id' => 'admin#ticket', as: :admin_ticket
    get '/tickets/new' => 'admin#new_ticket', as: :admin_new_ticket
    post '/tickets/create' => 'admin#create_ticket', as: :admin_create_ticket
    get '/tickets/update' => 'admin#update_ticket', as: :update_ticket, defaults: {format: 'js'}
    get '/tickets/update_multiple' => 'admin#update_multiple_tickets', as: :update_multiple_tickets
    get '/tickets/assign_agent' => 'admin#assign_agent', as: :assign_agent
    get '/tickets/toggle_privacy' => 'admin#toggle_privacy', as: :toggle_privacy
    get '/tickets/:id/toggle' => 'admin#toggle_post', as: :toggle_post
    get '/communities' => 'admin#communities', as: :admin_communities
    #get '/users'
    get '/user/:id/edit' => 'admin#edit_user', as: :admin_user
    get '/user/:id' => 'admin#user_profile', as: :user_profile
    get '/topic_search' => 'admin#topic_search', as: :admin_search
    get '/user_search' => 'admin#user_search', as: :user_search

  end




  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  login                  :string
#  identity_url           :string
#  name                   :string
#  admin                  :boolean          default(FALSE)
#  bio                    :text
#  signature              :text
#  role                   :string           default("user")
#  home_phone             :string
#  work_phone             :string
#  cell_phone             :string
#  company                :string
#  street                 :string
#  city                   :string
#  state                  :string
#  zip                    :string
#  title                  :string
#  twitter                :string
#  linkedin               :string
#  thumbnail              :string
#  medium_image           :string
#  large_image            :string
#  language               :string           default("en")
#  assigned_ticket_count  :integer          default(0)
#  topics_count           :integer          default(0)
#  active                 :boolean          default(TRUE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  provider               :string
#  uid                    :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => Devise.omniauth_providers

  validates :name, presence: true

  include Gravtastic

  include PgSearch
  pg_search_scope :user_search,
                  against: [:name, :login, :email, :company]

  paginates_per 15

  # Relationships
  has_and_belongs_to_many :roles
  has_many :topics
  has_many :posts
  has_many :votes
  has_many :docs
  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  is_gravtastic

  ROLES = %w[admin agent editor user]

  scope :admins, -> { where(admin: true).order('name asc') }

  def active_assigned_count
    Topic.where(assigned_user_id: self.id).active.count
  end

  def self.create_password
    Devise.friendly_token
  end

  def thumbnail_url
    self.thumbnail.blank? ? self.gravatar_url(size: 60) : self.thumbnail
  end

  def image_url
    self.medium_image || self.gravatar_url(size: 60)
  end

  def self.find_for_oauth(auth)
    if !where(email: auth.info.email).empty?
      user = find_by(email: auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user.save!
      user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
        u.provider = auth.provider
        u.uid = auth.uid
        u.email = auth.provider == 'twitter' ? "#{auth.info.nickname}@twitter.com" : auth.info.email
        u.name = auth.info.name
        u.thumbnail = auth.info.image
        u.password = Devise.friendly_token[0,20]
      end
    end
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/views/admin/_edit_user.html.erb
<!-- <div id="edit-user-info-horizontal" class="row">-->
  <%= bootstrap_form_for(@user, remote: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <div class='col-md-4 col-sm-12 col-xs-12 text-center' id='user-info-image'>
    <%= avatar_image(@user, size=150) %>
  </div>
  <div id="user-contact-info" class="col-md-4 col-sm-6 col-xs-12 user-info">
    <div class="tiny-header"><%= @user.name %></div>
    <span class="small">
      <%= f.text_field :name %>
      <%= f.text_field :company %>
      <%= f.text_field :city, inline: true %> <%= f.text_field :state, inline: true  %>
      <%#= @topic.user.country.titleize unless @topic.user.country.nil? %>
      <%= f.check_box :active, inline: true %> <%= f.check_box :admin, inline: true %>


    </span>
  </div>
  <div id="user-contact-info" class="col-md-4 col-sm-6 col-xs-12  user-info">
    <div class="tiny-header"><%= t(:contact_info, default: "Contact") %>:</div>
    <%= f.text_field :work_phone %>
    <%= f.text_field :cell_phone %>
    <%= f.email_field :email %><br/>
    <div class="tiny-header"><%= t(:social_info, default: "Social") %>:</div>
    <%= f.text_field :twitter %>
    <%= f.text_field :linkedin %>
    <%= f.submit "Save", class: 'btn btn-warning' %>
  </div>

  <% end %>
<!-- </div> -->

app/views/admin/_ticket.html.erb
<div id="ticket-info" class="no-side-pad row">

  <div class="col-md-4 hidden-xs hidden-sm" id="left-col-user-info">
    <%= render 'admin/user_info' %>
  </div>

  <div id="ticket-controls" class="col-md-8 col-xs-12 col-lg-8">
    <h2>
      <%= render 'admin/ticket_nav_dropdown' %> #<%= @topic.id %>- <%= @topic.name -%>
    </h2>
    <div id="topic-options">
    <%= render :partial => 'admin/topic_options' %>
    </div>
    <script>
      Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
    </script>
    <div id="posts">
    <%= render :partial => 'posts/post', :collection => @posts %>
    </div>


    <div class="add-form">
      <h4><%= t(:reply_to_this_topic, default: 'Reply to this Topic') %>:</h4>

      <%#= error_messages_for :post -%>

      <%= bootstrap_form_for @topic.posts.new, :url => topic_posts_path(@topic), :remote => true do |f| -%>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

        <%= f.form_group :kind  do %>
          <%= f.radio_button :kind, 'reply', label: t(:reply, default: "Reply"), checked: true, inline: true %>
          <%= f.radio_button :kind, 'note', label: t(:internal_note, default: "Internal Note"), inline: true %>
        <% end %>

        <%= hidden_field_tag :client_id %>
        <%= f.text_area :body, :rows => 8, :cols => 160, hide_label: true, placeholder: t(:type_reply, default: "Type your reply, or select from a common message below") %>
        <%= i18n_reply %>
        <%= f.attachinary_file_field :screenshots unless Cloudinary.config.cloud_name.nil? %>
        <%= f.submit t(:submit_reply), class: 'btn btn-warning' -%>
      <% end -%>

    </div>
  </div>


</div>

app/views/admin/_ticket_nav_dropdown.html.erb
<div id="status-mobile-dropdown" class="btn-group hidden-md hidden-lg hidden-sm pull-right">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <span class="status"><%#= status_label(@status) if @status %></span><span class="caret"></span>
  </button>
  <ul class="list-unstyled dropdown-menu" role="menu">
    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'new'), :remote => true do %>
      <%= t(:new, default: "New") %>
      <span class="tiny-header pull-right"><%= @unread %></span>
      <% end %>
    </li>

    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'pending'), :remote => true do %>
      <%= t(:pending, default:"Pending") %>
      <span class="tiny-header pull-right"><%= @pending %></span>
      <% end %>
    </li>
    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'assigned', :assigned_user_id => current_user), :remote => true do %>
      <%= t(:mine, default: "Mine") %>
      <span class="tiny-header pull-right"><%= @mine %></span>
      <% end %>
    </li>

    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'open'), :remote => true do %>
      <%= t(:open, default: "Open") %>
      <span class="tiny-header pull-right"><%= @open %></span>
      <% end %>
    </li>

    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'closed'), :remote => true do %>
      <%= t(:closed, default: "Resolved") %>
      <span class="tiny-header pull-right"><%= @closed %></span>
      <% end %>
    </li>
    <li class="mailbox tiny-header">
      <%= link_to admin_tickets_path(:status => 'spam'), :remote => true do %>
      Spam
      <span class="tiny-header pull-right"><%= @spam %></span>
      <% end %>
    </li>
    <li class="mailbox tiny-header">
      <%= link_to t(:open_new_discussion, default: "Create New Ticket"), admin_new_ticket_path, remote: true, class: 'btn btn-default' %>
    </li>
  </ul>
</div>

app/views/admin/_ticket_stats.html.erb
<div id="discussion-flow" class="hidden-xs">
  <div class="tiny-header"><%= t(:support_pipeline, default: "Support Pipeline") %>:</div>

  <div id="admin-stats" class="row">

    <!--
    <div class="col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">
        <h2><%= Topic.all.count %></h2>
        <%= link_to "All", admin_tickets_path(:status => 'all'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>
    -->

    <div class="has-arrow col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">
        <h2><%= @new %></h2>
        <%= link_to t(:new, default: "New"), admin_tickets_path(:status => 'new'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>

    <div class="has-arrow col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">

      <h2><%= @active %></h2>
      <%= link_to t(:active, default: "Active"), admin_tickets_path(:status => 'active'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>

    <div class="has-arrow col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">

        <h2><%= @open %></h2>
        <%= link_to t(:open, default: "Open"), admin_tickets_path(:status => 'open'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>
    <div class="has-arrow col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">

        <h2><%= @mine %></h2>
        <%= link_to t(:mine, default: "Mine"), admin_tickets_path(:status => 'assigned', :assigned_user_id => current_user), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>
    <div class="has-arrow col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">

        <h2><%= @pending %></h2>
        <%= link_to t(:pending, default:"Pending"), admin_tickets_path(:status => 'pending'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>

    <div class="col-md-2 col-sm-2 col-xs-2 text-center">
      <div class="dummy"></div>
      <div class="stats">
        <h2><%= @closed %></h2>
        <%= link_to t(:closed, default: "Resolved"), admin_tickets_path(:status => 'closed'), :remote => true, class: 'tiny-header admin-discussion-nav' %>
      </div>
    </div>

  </div>
</div>

app/views/admin/_topic.html.erb
<tr id="topic-<%= topic.id %>" class="topic border-bottom link-row admin-discussion">
  <td>
    <%= check_box_tag "topic_ids[]", topic.id, false, class: 'topic-checkbox pull-left' %>
    <span class="user-thumbnail pull-right hidden-xs">
      <%= link_to avatar_image(topic.user, size=40), user_profile_path(topic.user.id), remote: true %>
    </span>
  </td>

  <td>
    <span class="topic-link more-important truncate-ellipsis">
      <%= link_to "##{topic.id}- #{topic.name}", admin_ticket_path(topic), remote: true -%><%= badge_for_status(topic.current_status) %><%= badge_for_private if topic.private? %>
    </span>
    <span class="less-important user-link">
      <%= link_to t(:started_by, username: topic.user.name? ? topic.user.name.titleize : topic.user.email, default: "Started by #{topic.user.name? ? topic.user.name.titleize : topic.user.email}"), user_profile_path(topic.user.id), remote: true %>
      - <%= assigned_to(topic) %>
    </span>
  </td>

  <td class="last-active less-important text-right hidden-xs">
    <span class="label label-count hidden-xs pull-left"><%= topic.posts_count %></span>
    <%= last_active_time(topic.updated_at) %>
  </td>
</tr>

app/views/admin/_user_info_horizontal.html.erb
<div id="user-info-horizontal" class="row">

  <div class='col-md-4 col-sm-6 col-xs-12 text-center' id='user-info-image'>
    <%= avatar_image(@user, size=150) %>
  </div>
  <div class='hidden-sm hidden-xs col-md-2' style="height: 100px"><!-- spacer for design--></div>
  <div id="user-contact-info" class="col-md-3 col-sm-3 col-xs-6 user-info">
    <div class="tiny-header"><%= @user.name? ? @user.name.titleize : @user.email %> (<%= link_to t(:edit, default: 'Edit'), admin_user_path(@user), remote: true %>)</div>
    <span class="small">
      <%= @user.company.titleize unless @user.company.nil? %><br/>
      <%= @user.city.titleize + ', ' unless @user.city.nil? %> <%= @user.state.titleize unless @user.state.nil? %>
      <%#= @topic.user.country.titleize unless @topic.user.country.nil? %>
    </span>
  </div>
  <div id="user-contact-info" class="col-md-3 col-sm-3 col-xs-6  user-info">
    <div class="tiny-header"><%= t(:contact_info, default: "Contact") %>:</div>
    <%= t(:work_phone, default: "work") %>: <%= @user.work_phone %><br/>
    <%= t(:cell_phone, default: "cell") %>: <%= @user.cell_phone %><br/>
    <%= @user.email %><br/>
  </div>
  <div id="user-bio-info" class="col-md-3 col-sm-3 col-xs-6 user-info">
    <div class="tiny-header"><%= t(:bio, default: "Bio") %>:</div>
    <%= @user.bio %><br/>
  </div>

  <div id="user-social-info" class="col-md-3 col-sm-3 col-xs-6  user-info">
    <div class="tiny-header"><%= t(:social_info, default: "Social") %>:</div>
    Twitter: <%= @user.twitter %><br/>
    Linkedin: <%= @user.linkedin %><br/>
  </div>


</div>

app/views/admin/_users.html.erb
<table id="forums">
  <col width="5%">
  <col width="85%">
  <col width="10%">

  <%= render partial: 'user', collection: @users if @users %>
</table>

<div class="text-right">
  <%= paginate @users if @users %>
</div>

app/views/admin/dashboard.html.erb
<script>
$(document).ready(function(){
  $('.topic-box').click(function(){
    document.location.href = $(this).data("link");
  });
  $('.thumbnail').mouseover(function(){
    $(this).css('cursor','pointer');
    $(this).css('border','1px solid #666');
    $(this).css('box-shadow', '0px 0px 10px #eee');
  });
  $('.thumbnail').mouseout(function(){
    $(this).css('cursor','auto');
    $(this).css('border','1px solid #eee');
    $(this).css('box-shadow', '');
  });


});
</script>


<h1>Admin Dashboard</h1>

<div class="tiny-header">Discussion Flow</div>

<div id="admin-stats" class="row">
  <div class="col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">

      <h2><%= @closed %></h2>
      Resolved
    </div>
  </div>
  <div class="topic-box col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">
      <h2><%= Topic.all.count %></h2>
      All
    </div>
  </div>
  <div class="col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">

    <h2><%= @active %></h2>
    Active
    </div>
  </div>
  <div class="col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">

      <h2><%= @open %></h2>
      Open
    </div>
  </div>
  <div class="col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">

      <h2><%= @mine %></h2>
      Mine
    </div>
  </div>
  <div class="col-md-2 col-sm-2 col-xs-2 text-center">
    <div class="dummy"></div>
    <div class="thumbnail">

      <h2><%= @pending %></h2>
      Waiting
    </div>
  </div>
</div>

<table id="topics" class="forum table-hover">

  <col width="70%">
  <col width="30%">

  <tr>
    <th>Subject</th>
    <th class="text-right">Last Post</th>
  </tr>
  <tbody>
  <%= render :partial => 'topic', :collection => @topics %>
  </tbody>
</table>
<div class="text-right">
  <%= paginate @topics, remote: true %>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="topic-box col-md-3 col-sm-3 col-xs-6" data-link="<%= admin_users_path %>">
      <div class="dummy"></div>
      <div class="thumbnail">
        <h5 class="category-header text-center"><span class='category-icon glyphicon glyphicon-user'></span><br/><%= link_to 'Admin Team', admin_users_path  %><br/></h5>
        <p class="text-center less-important hidden-xs">See reports on individual users.</p>
      </div>
    </div>
    <div class="topic-box col-md-3 col-sm-3 col-xs-6" data-link="<%= admin_knowledgebase_path %>">
      <div class="dummy"></div>
      <div class="thumbnail">
        <h5 class="category-header text-center"><span class='category-icon glyphicon glyphicon-book'></span><br/><%= link_to "Content", admin_knowledgebase_path %><br/></h5>
        <p class="text-center less-important hidden-xs">Edit Knowledgebase, common replies, or other site content</p>
      </div>
    </div>
    <div class="topic-box col-md-3 col-sm-3 col-xs-6" data-link="<%= admin_tickets_path %>">
      <div class="dummy"></div>
      <div class="thumbnail">
        <h5 class="category-header text-center"><span class='category-icon glyphicon glyphicon-comment'></span><br/><%= link_to "Discussions", admin_tickets_path %><br/></h5>
        <p class="text-center less-important hidden-xs">Read and Resolve Support Discussions</p>
      </div>
    </div>
    <div class="topic-box col-md-3 col-sm-3 col-xs-6" data-link="<%= admin_communities_path %>">
      <div class="dummy"></div>
      <div class="thumbnail">
        <h5 class="category-header text-center"><span class='category-icon glyphicon glyphicon-align-justify'></span><br/><%= link_to "Community", admin_communities_path %><br/></h5>
        <p class="text-center less-important hidden-xs">Add or Remove Support Community Topics</p>
      </div>
    </div>
    <h4>Jump to User:</h4>
    <%= render 'user_search_form' %>
    <div id="users">
      <%= render 'users' %>
    </div>
  </div>
</div>

app/views/admin/doc.html.erb
<h1>Edit Document: <%= @doc.title %></h1>
<%= form_for :doc, url: category_doc_path(@category,@doc), method: 'patch' do |f| %>

  <%#= error_messages_for :doc %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>

  <%= f.text_area(:body, :width => '100%', :height => '400px') %>
  </p>

  <p>
    <%= f.label :meta_description %><br />
    <%= f.text_field :meta_description %>
  </p>

  <p>
    <%= f.label :title_tag %><br />
    <%= f.text_field :title_tag %>
  </p>

  <p>
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </p>

  <!--
  <p>
    <%#= f.label :tags %><br />
    <%#= text_field_tag :tags, @doc.tag_list %>
  </p>
  -->
  <p>
    <%= f.label :category %><br />
    <%= collection_select(:doc, :category_id, @categories, :id, :name) %> <%#= link_to 'Edit Categories', :controller => 'categories', :action => 'admin' %>
  </p>

  <p>
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </p>

  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :front_page %><br />
    <%= f.check_box :front_page %>
  </p>

  <p>
    <%= f.submit "Update", :class => 'submit' %>
  </p>

<% end %>
<%#= link_to 'Show', :doc %> |
<%#= link_to 'Back', category_path(category) %>

app/views/admin/edit_user.js.erb
$('#user-info-horizontal').html("<%= j render partial: 'edit_user' %>");

window.location.hash = 'edit_<%= @user.id %>';

app/views/admin/knowledgebase.html.erb
<script>
$(document).ready(function(){
  $('.toggle-controls').on("click", function(e){
    //get ID
    var id = e.target.id.split('-')[1];
    console.log('ID is ' + id);
    // reveal corresponding id controls
    $('#controls-' + id).removeClass('hidden');
  });
});
</script>

<h2><%= t(:content, default: 'Content') %><span class="admin-options text-right pull-right">
  <%= link_to t(:new_category, default: "New Category"), new_category_path(lang: I18n.locale), class: 'btn btn-primary' %>
  <%= link_to t(:new_content, default: "New Content"), new_doc_path(lang: I18n.locale), class: 'btn btn-primary' %>
</span></h2>



<div class="row">
  <div class="col-md-12">
    <table id="forums" class="table-hover sortable">
      <col>
      <col width="5%">
      <thead>
        <tr>
          <th colspan="2" class='tiny-header'><%= t(:front_page_categories, default: 'Front Page Categories') %></th>
        </tr>
      </thead>
      <tbody id="categories">
        <%= render partial: 'cat', collection: @categories %>
      </tbody>
    </table>

    <% if @nonfeatured.count > 0 %>
    <table id="forums" class="table-hover">
      <col>
      <col width="5%">
      <tbody id="categories">
        <tr>
          <td colspan="2"></td>
        </tr>
        <tr>
          <td colspan="2" class='tiny-header'><%= t(:other_categories, default: 'Other Categories') %></td>
        </tr>
        <%= render partial: 'cat', collection: @nonfeatured %>
      </tbody>
    </table>
    <% end %>

  </div>
</div>
<br/>

app/views/admin/ticket.js.erb
$('#tickets').html("<%= escape_javascript(render 'admin/ticket') %>");
$('.ticket-stats').html("<%= j render 'admin/ticket_stats' %>");
//$('#left-col-ticket-nav').html("<%= escape_javascript(render 'admin/ticket_nav') %>");
//$('#ticket-page-title').html("#<%= @topic.id %> <%= @topic.name.titleize %> <span class='hidden-xs pull-right'> <%= escape_javascript(render 'admin/ticket_nav_dropdown') %>");
$('#ticket-page-title').html("").hide();
$(document).prop('title', "Discussion Management: #<%= @topic.id %> <%= @topic.name.titleize %>");
window.location.hash = '<%= "#{@topic.id} #{@topic.name}" %>';

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// Send ping to GA
ga('send', 'pageview');

// jQuery hook
Helpy.ready();
Helpy.track();

app/views/admin/tickets.html.erb
<%#= render 'admin/ticket_stats' %>

<h2 id="ticket-page-title">
  <%= t(:discussions, default: "Discussions") %>: <span class='label <%= status_class(@status) %>' style='text-transform: uppercase'><%= status_label(@status) if @status %></span> <%= render 'admin/ticket_nav_dropdown' %> <span class="hidden-xs pull-right"><%= link_to t(:open_new_discussion, default: "Open Discussion"), admin_new_ticket_path, remote: true, class: 'btn btn-primary' %></span>
</h2>

<div class="row">
  <div class="col-md-3 hidden-lg hidden-md hidden-xs hidden-sm" id="left-col-ticket-nav">
    <%= render 'ticket_nav' %>
  </div>

  <div class="col-md-12" id="tickets">
    <%= render 'tickets' %>
  </div>


</div>

app/views/admin/update_ticket.js.erb
$('#tickets').html("<%= escape_javascript(render 'admin/ticket') %>");
$('.ticket-stats').html("<%= j render 'admin/ticket_stats' %>");
//$('#left-col-ticket-nav').html("<%= escape_javascript(render 'admin/ticket_nav') %>");

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// jQuery hook
Helpy.ready();
Helpy.track();