config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'registrations' }

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit] do
      #collection do
      #  get 'admin'
      #end
      resources :docs, except: [:new, :edit]
    end

    resources :docs, except: [:new, :edit]
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts

    resources :users

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote
    get 'result' => 'result#index', as: :result
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale
  get '/set_client_id' => 'users#set_client_id', as: :set_client_id

  # Admin Routes

  scope 'admin' do

    get '/' => 'admin#tickets', as: :admin

    resources :docs, only: [:new, :edit]
    resources :knowledgebase, :as => 'categories', :controller => "categories", only: [:new, :edit] do
      resources :docs, only: [:new, :edit]
    end

    get '/dashboard' => 'admin#dashboard', as: :admin_dashboard
    get '/content' => 'admin#knowledgebase', as: :admin_knowledgebase
    get '/content/:category_id/articles' => 'admin#articles', as: :admin_articles
    post '/content/update_order' => 'admin#update_order', as: :admin_update_order
    get '/tickets' => 'admin#tickets', as: :admin_tickets
    get '/ticket/:id' => 'admin#ticket', as: :admin_ticket
    get '/tickets/new' => 'admin#new_ticket', as: :admin_new_ticket
    post '/tickets/create' => 'admin#create_ticket', as: :admin_create_ticket
    get '/tickets/update' => 'admin#update_ticket', as: :update_ticket, defaults: {format: 'js'}
    get '/tickets/update_multiple' => 'admin#update_multiple_tickets', as: :update_multiple_tickets
    get '/tickets/assign_agent' => 'admin#assign_agent', as: :assign_agent
    get '/tickets/toggle_privacy' => 'admin#toggle_privacy', as: :toggle_privacy
    get '/tickets/:id/toggle' => 'admin#toggle_post', as: :toggle_post
    get '/communities' => 'admin#communities', as: :admin_communities
    #get '/users'
    get '/user/:id/edit' => 'admin#edit_user', as: :admin_user
    get '/user/:id' => 'admin#user_profile', as: :user_profile
    get '/topic_search' => 'admin#topic_search', as: :admin_search
    get '/user_search' => 'admin#user_search', as: :user_search

  end




  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  topic_id   :integer
#  user_id    :integer
#  body       :text
#  kind       :string
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  points     :integer          default(0)
#

class Post < ActiveRecord::Base

  attr_accessor :reply_id

  belongs_to :topic, counter_cache: true, touch: true
  belongs_to :user, touch: true
  has_many :votes, :as => :voteable
  has_attachments :screenshots, accept: [:jpg, :png, :gif]

  validates_presence_of :body, :kind
  validates_length_of :body, :maximum => 10000

  after_create  :update_waiting_on_cache
  after_save  :update_topic_cache
  #after_save :send_message

  scope :all_by_topic, -> (topic) { where("topic_id = ?", topic).order('updated_at ASC').include(user) }
  scope :active, -> { where(active: true) }
  scope :ispublic, -> { where.not(kind: 'note') }
  scope :chronologic, -> { order('created_at ASC') }
  scope :by_votes, -> { order('points DESC')}

  #updates the last post date for both the forum and the topic
  #updates the waiting on cache
  def update_waiting_on_cache

    status = self.topic.current_status
    waiting_on = self.topic.waiting_on

    #unless status == 'closed' || status == 'trash'
    unless status == 'trash'
      logger.info('private message, update waiting on cache')
      status = self.topic.current_status
      if self.user && self.user.admin?
        logger.info('waiting on user')
        waiting_on = "user"
        status = "open"
      else
        logger.info('waiting on admin')
        waiting_on = "admin"
        status = "pending" unless self.topic.current_status == 'new'
      end
    end

    self.topic.update(last_post_date: Time.now, waiting_on: waiting_on, current_status: status)
    self.topic.forum.update(last_post_date: Time.now)
  end

  #updates cache of post content used in search
  def update_topic_cache
    unless self.kind == 'note'
      current_cache = self.topic.post_cache
      self.topic.update(post_cache: "#{current_cache} #{self.body}")
    end
  end

end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  topic_id   :integer
#  user_id    :integer
#  body       :text
#  kind       :string
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  points     :integer          default(0)
#

class PostsController < ApplicationController

  before_action :authenticate_user!, :except => ['index', 'create', 'up_vote']
  before_action :verify_admin, :only => ['new', 'edit', 'update', 'destroy']
  before_action :instantiate_tracker

#  before_filter :fetch_counts, :only => 'create'
  after_action :send_message, :only => 'create'
#  after_filter :view_causes_vote, :only => 'index'

  layout "clean", only: [:index]


  def index
    @topic = Topic.undeleted.ispublic.where(id: params[:topic_id]).first#.includes(:forum)
    if @topic
      @posts = @topic.posts.ispublic.active.all.chronologic
      @post = @topic.posts.new

      #@related = Topic.ispublic.by_popularity.front.tagged_with(@topic.tag_list)

      #@feed_link = "<link rel='alternate' type='application/rss+xml' title='RSS' href='#{topic_posts_url(@topic)}.rss' />"

      @page_title = "#{@topic.name}"
      @title_tag = "#{Settings.site_name}: #{@page_title}"
      add_breadcrumb t(:community, default: "Community"), forums_path
      add_breadcrumb @topic.forum.name, forum_topics_path(@topic.forum)
      add_breadcrumb @topic.name
    end

    respond_to do |format|
      if @topic
        format.html # index.rhtml
      else
        format.html { redirect_to root_path}
      end
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.rhtml
    end
  end

  def new
    @topic = Topic.find(params[:topic_id], :include => :forum)
    @post = Post.new
    @forums = Forum.all
  end

  def edit
    @post = Post.where(id: params[:id]).first

    respond_to do |format|
      format.js
    end
  end

  def cancel
    @post = Post.where(id: params[:id]).first

    respond_to do |format|
      format.js
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(:body => params[:post][:body],
                     :topic_id => @topic.id,
                     :user_id => current_user.id,
                     :kind => params[:post][:kind],
                     :screenshots => params[:post][:screenshots])

    respond_to do |format|
      if @post.save

        format.html {
          @posts = @topic.posts.ispublic.chronologic.active
          redirect_to topic_posts_path(@topic)
        }
        format.js {
          if current_user.admin?
            fetch_counts

            @posts = @topic.posts.chronologic
            @admins = User.admins
            #@post = Post.new
            case @post.kind
            when "reply"
              @tracker.event(category: "Agent: #{current_user.name}", action: "Agent Replied", label: @topic.to_param) #TODO: Need minutes
            when "note"
              @tracker.event(category: "Agent: #{current_user.name}", action: "Agent Posted Note", label: @topic.to_param) #TODO: Need minutes
            end
            render 'admin/ticket'

          else #current_user is a customer
            @posts = @topic.posts.ispublic.chronologic.active
            unless @topic.assigned_user_id.nil?
              agent = User.find(@topic.assigned_user_id)
              @tracker.event(category: "Agent: #{agent.name}", action: "User Replied", label: @topic.to_param) #TODO: Need minutes
            end
          end

        }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.body = params[:post][:body]
    @post.active = params[:post][:active]

    respond_to do |format|
      if @post.save
        format.js
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
       format.html { redirect_to topic_posts_path(@post.topic) }
    end
  end

  def up_vote

    if user_signed_in?
      @post = Post.find(params[:id])
      @post.votes.create(user_id: current_user.id)
      @topic = @post.topic
      @topic.touch
      @post.reload
    end

    respond_to do |format|
      format.js
    end

  end


  protected

  def send_message
    #Should only send when admin posts, not when user replies

    if current_user.admin?
      if @post.kind == 'first'
        email_locale = I18n.locale
      else
        email_locale = @topic.locale.nil? ? I18n.locale : @topic.locale.to_sym
      end

      I18n.with_locale(email_locale) do
        TopicMailer.new_ticket(@post.topic).deliver_now if @topic.private?
      end
    else
      logger.info("reply is not from admin, don't email") #might want to cchange this if we want admin notification emails
    end
  end

  def view_causes_vote
    if logged_in?
      @topic.votes.create unless current_user.admin?
    else
      @topic.votes.create
    end
  end
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  topic_id   :integer
#  user_id    :integer
#  body       :text
#  kind       :string
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  points     :integer          default(0)
#

module PostsHelper

  def post_message(post)

    case post.kind
    when 'first'
      message = t(:asked_a_question, user_name: post.user.name.titleize ,default: "asked a question...")
    when 'reply'
      message = t(:replied, user_name: post.user.name.titleize, default: "replied...")
    when 'note'
      message = t(:posted_note, user_name: post.user.name.titleize, default: "posted an internal note...")
    end
    if user_signed_in? && current_user.admin? && params[:controller] == 'admin'
      content_tag(:span, class: 'btn dropdown-toggle more-important', data: { toggle: 'dropdown'}, aria: {expanded: 'false'}) do
        "#{message} <span class='caret'></span>".html_safe
      end
    else
      content_tag(:span, class: 'more-important') do
        "#{message}".html_safe
      end
    end
  end

  def vote_widget(topic)
    content_tag(:div, class: "voting-widget") do
      content_tag(:div, class: "vote-icon glyphicon glyphicon-chevron-up")
      content_tag(:div, class: "topic_points") do
        link_to topic.points, up_vote_path(topic.id), method: :post, remote: true
      end
    end
  end

  def post_admin

  end

end

app/views/posts/_edit.html.erb
<%= bootstrap_form_for :post, :url => topic_post_path(:id => @post, :topic_id => @post.topic,
                                     :forum_id => @post.topic.forum),
                                     :html => {:method => :put}, remote: true do |f| -%>
  <%= f.text_area :body, :rows => 8, :cols => 60, hide_label: true -%></p>
  <%= f.check_box :active %>
  <%= f.submit 'Save Changes' -%> or
  <%= link_to 'Cancel', cancel_edit_post_path(id: @post), remote: true, class: 'cancel-edit', id: "cancel-edit-#{@post.id}" -%>
<% end -%>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="media post-container <%= "kind-#{post.kind}" %><%= post.topic.forum.allow_post_voting? ? "" : " disallow-post-voting" %><%= " inactive" unless post.active? %>">
	<div class="pull-left">
		<%#= image_tag(user_avatar(post.user), width: '40px', class: 'media-object img-circle') %>
		<%= avatar_image(post.user, size=40) %>
	</div>
	<div class="media-body media-right">
		<span class="hidden-sm hidden-md hidden-lg"><%= post.kind == "first" ? last_active_time(post.created_at) : "#{distance_of_time_in_words(post.created_at,post.topic.created_at)} later" %><br/></span>
		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
			<%= post_message(post) %>
			<% if user_signed_in? && current_user.admin? && params[:controller] == 'admin' %>
				<ul class="dropdown-menu dropdown-menu-left" role="menu">
					<li><%= link_to 'Edit', edit_post_path(post), remote: true %></li>
					<li><%= link_to 'Turn post into content', new_doc_path(post_id: post.id, lang: I18n.locale) %></li>
				</ul>
			<% end %>
		</span>

		<span class="last-active posted-at less-important pull-right">
			<span class="hidden-xs">
			<%= post.kind == "first" ? last_active_time(post.created_at) : "#{distance_of_time_in_words(post.created_at,post.topic.created_at)} later" %>
			</span>
		</span>

		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
			<%= simple_format(post.body) -%>
			<% if post.topic.forum.allow_post_voting == true %>
			<div id="post-vote-<%= post.id %>" class="btn btn-default">
				<% if post.kind == 'first' %>
				<%= link_to t(:upvote, count: post.topic.points), up_vote_path(post.topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: post.topic.to_param} %>
				<% else %>
				<%= link_to t(:upvote, count: post.points), post_vote_path(post.id), method: :post, remote: true, class: 'post-vote', data: {voted: post.id} %>
				<% end %>
			</div>
			<% end %>
			<% unless Cloudinary.config.cloud_name.nil? %>
			<div id="post-images">
				<ul class="list-inline">
					<% post.screenshots.each do |screenshot| %>
						<li><%= link_to cl_image_tag(screenshot.path, { size: '125x125', crop: :fit }), "http://res.cloudinary.com/#{Cloudinary.config.cloud_name}/image/upload/#{screenshot.path}", class: 'screenshot-link' %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
		</div>

		<% if user_signed_in? && post.kind == 'first' && post.topic.forum.allow_post_voting == true && params[:controller] != 'admin'   %>
			<div class="add-form inline-reply">
			<h4><%= t(:reply) %></h4>
			<%#= error_messages_for :post -%>
			<%= bootstrap_form_for :post, :url => topic_posts_path(@topic) do |f| -%>
			  <%= f.text_area :body, :rows => 4, :cols => 160, label: 'Type your response:' -%></p>
			  <%= f.hidden_field 'kind', value: 'reply' %>
				<div class="add-screenshots">
				<%= attachinary_file_field_tag 'post[screenshots]', @topic.posts.new, :screenshots unless Cloudinary.config.cloud_name.nil? %>
				</div>
				<%= hidden_field_tag :client_id %>
				<%= f.submit t(:submit_reply) -%>
			<% end -%>
			</div>
		<% end -%>

	</div>
</div>

app/views/posts/_topic_stats.html.erb
<div>
	<%= @topic.current_status %>
</div>
<div id="topic-vote">
	<div class="topic-points">
		<%= @topic.points %>
	</div><br/>
	Number of People who liked this:<br/>

	<br/><%#= link_to_remote('Vote Down', :url => {:controller => 'topics', :action => 'down_vote', :id => @topic.id}) if user_signed_in? %>
</div>

<% if user_signed_in? %>
<h3>Vote it Up? <%= link_to(image_tag('icons/001_18.png'), :url => {:controller => 'topics', :action => 'up_vote', :id => @topic.id}, :class => 'button positive', :remote => true) %></h3>
<% end %>

<% if user_signed_in? && current_user.admin? %>
	<h3>Admin Tools:</h3>
	<div class="admin-tools">

			<%= link_to 'Edit', edit_topic_path(@topic) %><br/>
			Change Status:
			<% form_for(:topic, :url => forum_topic_path(@topic.forum, @topic.id), :method => 'put', :remote => true) do |f| %>
				<%= f.select(:current_status, [['Open'],['Resolved'],['Spam']], {}, :onchange => 'this.form.onsubmit();') %>
				<%#= f.submit 'Save' -%>
			<% end -%>
	</div>
<% end %>

<% if user_signed_in? %>
	<% if @topic.user_id == current_user.id || current_user.admin? %>
	<h3>Options:</h3>
	<div id="private-button">
		<% if @topic.private? %>
			<%= button_to 'Make Public', make_private_path(@topic,false) %>
		<% else%>
			<%= button_to 'Make Private', make_private_path(@topic,true) %>
		<% end %>
	</div>
	<% end %>
<% end %>

<!--
<%# unless @topic.tag_list.blank? %>
<h3>Tags:</h3>
<div id="tagged-with">
	<p><%#= @topic.tag_list %></p>
</div>
<%# end %>
-->

<% unless @related.blank? %>
<h3>Related Topics:</h3>
<div class="topic-related">
	<table>
	<% @related.each do |t| %>
		<tr>
			<td>
			<div class="topic-points">
					<%= t.points %>
			</div>
			</td>
			<td><%= link_to t.name, topic_posts_path(t) %></td>
		</tr>
	<% end %>
	</table>
</div>
<% end %>

app/views/posts/cancel.js.erb
$('#post-body-<%= @post.id %>').html("<%= j simple_format(@post.body) %>");

app/views/posts/create.js.erb
$('#posts').append('<%= j render(partial: 'post', locals: { post: @post }) %>');

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// jQuery hook
//Helpy.ready();
//Helpy.track();

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%#= error_messages_for :post -%>
<h3>Topic: <%= @post.topic.name %></h3>

app/views/posts/edit.js.erb
$('#post-body-<%= @post.id %>').html("<%= j render 'posts/edit' %>");

app/views/posts/index.html.erb
<div class="row">

	<div class="col-md-12">
		<script>
			Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
		</script>

		<table id="posts">
			<%= render :partial => 'post', :collection => @posts %>
		</table>


		<% if user_signed_in? && !@topic.forum.allow_post_voting == true %>
		<div class="add-form">
			<h4><%= t(:reply) %></h4>
			<%#= error_messages_for :post -%>
			<%= bootstrap_form_for :post, :url => topic_posts_path(@topic) do |f| -%>
			  <%= f.text_area :body, :rows => 8, :cols => 160, label: 'Type your response:' -%></p>
			  <%= f.hidden_field 'kind', value: 'reply' %>
				<div class="add-screenshots">
				<%= attachinary_file_field_tag 'post[screenshots]', @post, :screenshots unless Cloudinary.config.cloud_name.nil? %>
				</div>
				<%= hidden_field_tag :client_id %>
				<%= f.submit t(:submit_reply) -%>
			<% end -%>
			</div>
		<% else %>
			<span class="hidden-xs pull-right"><%= link_to t(:reply, default: "Reply"), '#', data: {toggle: "modal", target: "#login-modal"}, class: 'btn btn-primary' %></span>
		<% end -%>

	</div>

</div>

app/views/posts/new.html.erb
<div id="breadcrumbs">
  <%= link_to 'Forums', forums_path -%> >
  <%= link_to @topic.forum.name, forum_path(@topic.forum) -%> >
</div>
<h1>New Reply</h1>
<%= error_messages_for :post -%>

<% form_for @post, :url => topic_posts_path(@topic) do |f| -%>
  <p>Message:<br /><%= f.text_area :body, :rows => 8, :cols => 60 -%></p>
  <%= submit_tag 'Save' -%> or 
  <%= link_to 'Cancel', topics_path(:id => @topic, :forum_id => @topic.forum) -%>
<% end -%>

app/views/posts/up_vote.js.erb
<% if user_signed_in? %>
$('#post-<%= @post.id %>').replaceWith("<%= j(render partial: 'posts/post', locals: {post: @post}) %>");
<% else %>
$('.login-link').click();
<% end %>

app/views/posts/update.js.erb
//$('#post-<%= @post.id %>').replace("<%= j render partial: 'posts/post', locals: {post: @post} %>");
$('#post-body-<%= @post.id %>').html("<%= j simple_format(@post.body) %>");